export const getUsers = (req, res) => {
    try {

    } catch (error) {
        
    }
}